---
title: Cosas que deben cambiar
date: '2019-09-10'
-categories:
  - 2019
  - estadística
  - universidad
  - empresa
  - educación
description: ''
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>"
---

La semana pasada estuve en la bella ciudad de Alcoy en el [congreso de Estadística e Investigación Operativa](https://seio2019.com/es/) gracias a que nos invitaron a dar una sesión invitada presentando la [Comunidad R-hispano](http://r-es.org/). 

Como estoy en el mundo de la empresa mi percepción fue que, salvo en las charlas de investigación operativa, la distancia entre lo que se hace y se enseña en la universidad y lo que se utiliza en la empresa  es bestial. 

Lo peor de todo es que después de hablar con varios profesores allí presentes me invadió el pesimismo, los planes de estudios están obsoletos, se enseña mucha teoría y apenas hay algo que se parezca a un ejercicio que tenga el más mínimo parecido con lo que luego se van a encontrar esos alumnos en el mundo real.

En esta era de palabras grandilocuentes como `big data`, `machine learning`, `reinforcement learning` o `real time analytics` los informáticos están ganando la batalla a los matemáticos y estadísticos,  son ellos los que están adaptando sus planes de estudio, son ellos los que están creando los masters de ciencia de datos, y los pocos profesores de matemáticas o estadística que quieren colaborar con los informáticos en crear grados y másters adecuados se encuentran a menudo con las reticencias cuando no negativa de sus propios departamentos.

Afortunadamente en otros lugares del planeta hay gente que está poniendo las bases matemáticas formales para todas estas técnicas, entre los que cabe destacar a Friedman, Tibshirani, Hastie o Efron. 

Os dejo las referencias a un par de libros, que todo analista de datos debería tener en su colección.

* [Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/)
* [Computer Age Statistical Inference:
Algorithms, Evidence and Data Science](https://web.stanford.edu/~hastie/CASI/)

Así que, aún queda esperanza..

