project:
  type: website

format:
  html:
    theme: 
      light: theme.scss

website:
  title: "Muestrear no es pecado"
  site-url: https://muestrear-no-es-pecado-rebranding.netlify.app/
  description: "Estadística, ciencia de datos, big data, cosas varias"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/joscani
      - icon: twitter
        href: https://twitter.com/joscani
      - icon: mastodon
        href: https://fosstodon.org/@joscani 
      - icon: rss
        href: blog.xml
      - text: Resources
        menu: 
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/ 
          - text: Datanalytics
            href: https://www.datanalytics.com/
            
      - text: Archivo
        href: archive.qmd

filters:
  - lightbox

lightbox: auto
#########################  
  
editor: source


