project:
  type: website

format:
  html:
    theme: 
        light: flatly
        dark: darkly
website:
  title: "Muestrear no es pecado"
  site-url: https://muestrear-no-es-pecado.netlify.app/
  description: "Estadística, ciencia de datos, big data, cosas varias"
  page-navigation: true
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/joscani
      - icon: bluesky
        href: https://bsky.app/profile/joscani.muestrear-no-es-pecado.es
      - icon: twitter
        href: https://x.com/joscani
      - icon: mastodon
        href: https://fosstodon.org/@joscani 
      - icon: rss
        href: blog.xml
      - text: Resources
        menu: 
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/ 
          - text: Datanalytics
            href: https://www.datanalytics.com/
            
      - text: Archivo
        href: archive.qmd

filters:
  - shinylive

#########################  
  
editor: source


