---
title: "Guarnición de guerra"  
date: '2024-02-16'
categories: 
  - 2024
  - curro
description: ''
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8
    fig-align: center
    code-fold: show
    code-summary: "Show the code"
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>"
---

*Se conoce como guarnición a las tropas que protegen y están destinadas en un palacio, un castillo, un fuerte, 
un buque de guerra o una zona o región, por ejemplo.*


Esta semana ha sido *interesante* en el curro. He vivido lo que en el argot se conoce como "war room". Básicamente tiene que ver
con que hay algo que ha fallado o se ha retrasado - típicamente en producción - y nadie tiene ni puta idea de por qué ha pasado. 

Es entonces cuando se convoca la "war room" , "gabinete de crisis" o "guarnición de guerra". Consiste en montar reunión durante 
prácticamente todo el día y durante varios días , y se convoca a los equipos implicados. A saber, gente que se encarga de las operaciones 
en producción, el equipo de desarrollo, e incluso gente de negocio si fuera necesario. Durante estas reuniones se trabaja codo con codo 
en intentar solucionar el problema y todo lo demás pasa a ser secundario. 

Ha sido mi primera "war room" en la empresa dónde curro y a pesar de la situación, que era crítica, ha sido una buena experiencia. 
Por un lado se ha mandado a tomar por saco todas las tonterías del agile y demás historias, aquí se está para currar y solucionar el problema. 
La gente en ningún momento ha echado nada en cara al otro equipo , ya sabéis , en plan "tú código es una mierda" y blablalba. 
En estas war rooms se valora a la gente resolutiva, que ofrece soluciones, se escucha a todo el mundo, porque incluso aunque se digan cosas 
que a priori pueden ser una locura, puede que hagan pensar en alguien en la posible solución. 


Y tengo que hablar de la gente, al menos en esta "guarnición de guerra" , la gente ha sido lo mejor. La gente de operaciones son muy profesionales, 
colaboradores, y tienen una paciencia infinita. La gente de mi equipo igual, unos cracks todos. He aprendido muchísimo y sobre todo valoro mucho más 
a la gente con la que trabajo.  

No sé si daremos con la tecla del problema, y puede que no sea lo más importante, lo que si sé es que compartir trinchera forja alianzas. 

Por mi parte, puede que de esta "guarnición de guerra" me gane unas cuántas cervezas, pues para cada hipótesis que se me ocurría de dónde pudiera estar 
el problema ( y una de las hipótesis que defiendo es que ha sido todo fruto del azar)  me apostaba un par de cervezas con alguien. 
" Me juego 2 cervezas a que esto no falla más en lo que queda de mes" ( ya lleva varios días seguidos sin fallar, la actualización de mi posteriori 
me da pie a pensar que voy a ganar la apuesta) o cosas así. 

La sensación es rara, por un lado ha habido problemas con cosas del proyecto y aún no tenemos claro por qué. Por otro lado, el compartir trinchera y 
trabajar todos a una en intentar solucionarlo me ha gustado mucho, y ha hecho que valore aún más a la gente de operaciones. 
Gracias a todos y feliz fin de semana. 

**Seguimos el lunes**


