---
title: "Nomenclatura"  
date: '2024-02-24'
categories: 
  - 2024
  - estadística
  - tiempos modernos
description: ''
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8
    fig-align: center
    code-fold: show
    code-summary: "Show the code"
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>"
---

A mis cuarenta y pocos tacos, como decía Sabina. El título de la entrada tiene que ver con algo que me llamó la atención 
de cuando empecé a currar en cosas de estas del Big Data. Se trata del cambio de denominación de ciertas cosas. 


Algunos ejemplos. 

* Llamar modelo multiclase a lo que siempre llamé __modelo multinomial__. 
* Modelo multioutput a lo que siempre llamé __modelo multivariante__ (más de una variable dependiente)
* Análisis supervisado / no supervisado a lo que se conocía como __modelos de dependencia y modelos de interdependencia.__
* Instancia a lo que siempre se ha denominado __observación__
* Regresor o clasificador  a lo que llamaba __modelos de regresión__ o __modelos de respuesta discreta__


Sin hablar de que la denominación del oficio ha pasado desde "el de los datos que está en el sótano", hasta 
"experto en IA, ML , fullstack DS" pasando por los más normales de "Analista de datos", "Minero de datos" o similar. 


Yo simplemente me considero un estadístico que sabe algo de estadística y algo de programación y tecnología. 

No sé si hablaremos de este tema  en próximos episodios del [podcast](https://open.spotify.com/show/3Ku9xHJdqu4g3VM5maolr7?si=44d43ab344014636)
que tenemos Leo y yo. 

Feliz día. 

