---
title: La fatal arrogancia
date: '2019-11-30'
categories:
  - ciencia de datos
  - 2019
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
    code-fold: show
    code-summary: "Mostrar / ocultar código"
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
---

::: callout-important
No, no voy a hablar de liberalismo ni de Hayek. Solo quería hacer una
pequeña reflexión sobre las nuevas generaciones de científicos de datos
o como se les quiera llamar.
:::

Vengo observando hace cosa de 3 años, que las nuevas generaciones creen
que es fácil utilizar modelos estadísticos (o de Machín Lenin como dice
algún amigo mío) para predecir cosas como la bolsa, o acertar ,cual
demiurgo, si se va a sufrir un cáncer y cosas por el estilo.

La fatal arrogancia a la que me refiero es aquella que hace que hasta
los que trabajamos en estos temas, nos dejemos llevar por el "hype" (no
sé bien como traducir esto) que se vive actualmente y nos creamos la
cantidad de mentiras que se dicen. Es fácil entusiasmarse por cosas como
el deep learning, reinforcement learning o el último algoritmo de
boosting, pero ninguna de estas cosas puede hacer magia y separar
totalmente la señal del ruido.

También noto lo de la fatal arrogancia entre aquellos que dicen que para
qué necesitan saber estadística, ¿a cuántos conocéis que den intervalos
de confianza o de credibilidad en vez de solo estimaciones puntuales?
Seguramente a muy pocos.

En fin, de lo que estoy seguro es que si hay alguno que ha conseguido a
predecir con éxito notable los movimientos de la bolsa, lo que menos
hace es alardear de su éxito dando charlas en meetups.

Nos vemos en los bares.
