---
title: Predicción, Estimación y Atribución
date: '2020-06-07'
slug: predicción-estimación-atribución
categories:
  - estadística
  - ciencia de datos
  - 2020
description: ''
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
    code-fold: show
    code-summary: "Mostrar / ocultar código"
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>" 
---


El título no es mío sino del gran [Bradley Efron](https://en.wikipedia.org/wiki/Bradley_Efron) que a sus 82 años aún sigue dando guerra. Acaba de salir publicado un [artículo](https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1762613) con el título que acabo de plagiarle  en JASA y la verdad es que estoy bastante de acuerdo con algunas de las cosas que plantea, o al menos es un debate interesante en estos tiempos.  

Deja algunas perlitas como __**If random forests had been around since 1908 and somebody just invented regression model significance testing, the news media might now be heralding an era of “sharp data.”**__ o __**Abandoning mathematical models comes close to abandoning the historic scientific goal of understanding nature.**__ .

En realidad el artículo es un conjunto de disquisiciones sobre las técnicas utilizadas hoy en día y sobre sus limitaciones, a mi personalmene me ha parecido muy interesante y creo que todo científico de datos debería leerlo.  En parte me ha recordado cuando hablaba con un compañero y yo le comentaba que con un xgboost (con las suficientes variables) se podría predecir con bastante exactitud el lugar dónde caerá un tiro parabólico o el tiempo que va a tardar en caer el proyectil, pero que nos ayudaría poco en descubrir la ley física que hay detrás.

Supongo que se me puede rebatir en plan, ¿y que más da, si predice bien? pero como dice Bradley __**Most traditional regression methods depend on some sort of surface plus noise formulation (though “plus” may refer to, say, binomial variability). The surface describes the scientific truths we wish to learn, but we can only observe points on the surface obscured by noise. The statistician’s traditional estimation task is to learn as much as possible about the surface from the data**__  y no sé, si nos llamamos a nosotros mismos científicos.

Un saludo, y leeros el artículo, en serio, es muy interesante.



