---
title: Tendencias
date: '2021-01-07'
categories:
  - ciencia de datos
  - estadística
  - causal inference
  - 2021
description: ''
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
    code-fold: show
    code-summary: "Mostrar / ocultar código"
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>"
---


Hoy, mi amigo [Jesús Lagos](https://twitter.com/Vdot_Spain/) ha retuiteado una entrevista que ambos consideramos bastante mala, [tweet](https://twitter.com/Vdot_Spain/status/1347011421423497219), y el caso es que me ha hecho reflexionar sobre un par de tendencias que veo en el sector. 

* Inferencia causal
* Algoritmos éticos ("fairness")
* Otras cosas


No se trata de bandos, pero si tuviera que elegir uno, me quedaría en el de la inferencia causal. Eso sí, ahora mismo está de moda y parece que antes de Pearl no había nada. Un par de reflexiones sobre esto, desde mi escaso conocimiento. 
Una, en inferencia causal tenemos el [Rubin Causal Model](https://en.wikipedia.org/wiki/Rubin_causal_model) desde hace ya unos añitos y según comentan quienes saben de esto es matemáticamente equivalente a los DAGs de Judea.
Por otro lado tambień se tiene todo el aparataje de los economistas, (las diferencias en diferencias, variables instrumentales, etc) , y también lo relacionado con los modelos de ecuaciones estructurales.  

En fin, todo este mundo de la inferencia causal tiene como objetivo poder detectar el efecto de un tratamiento o variable cuándo tenemos estudios observacionales, en experimentales todo lo anterior sobra. Dicho esto, es un campo interesante y con algunas aplicaciones, aunque creo que muchas veces nos complicamos la vida demasiado. 


Respecto a lo de los algoritmos éticos, limpios, no discriminatorios o como demonios los llamen, mejor me reservo mi opinión (el que la quiera que me invite a una birra en una terraza), simplemente leed el artículo del tweet con espíritu crítico (y sin que os salga la carjada ante tamañas barbaridades). 

Y con respecto a otras cosas, creo que en el mundo de la biología y la genética hay bastante potencial en cuánto al análisis de datos, y digo creo porque no tengo ni idea de ese ámbito y sólo ahora lo estoy atisbando. 


Nota1. Para los interesados en tener una visión introductoria de la inferencia causal topé el otro día con este libro online, que no tiene mala pinta. [Causal inference: The Mixtape](https://mixtape.scunning.com/index.html). Para profundizar más en el libro (que no he leído aún ) de Miguel Hernán [Causal Inference. What if](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/). En el caso del primero viene con código en stata y en R, y en el de segundo hay código en SAS, stata, R y python. Y librería en R para lo que llama parametric [g-formula](https://github.com/CausalInference/gfoRmula) 

Nota2. Respecto a la inferencia causal no hay que dejar de leer a Gelman, [Reseña de Gelman sobrre book of why](https://statmodeling.stat.columbia.edu/2019/01/08/book-pearl-mackenzie/)

Nota3. Iba a hablar más sobre los algoritmos éticos pero me da tanta pereza. Eso sí, estoy abierto a qué me recomendéis lecturas sobre el tema. 

Y nada más.
