---
title: Kiss
date: '2025-07-04'
categories: 
  - estadística
  - ciencia de datos
  - "2025"
description: ''
execute: 
  message: false
  warning: false
  echo: true
  output: true
format: 
  html: 
    toc: true
    fig-height: 5
    fig-dpi: 300
    fig-width: 8
    fig-align: center
    code-fold: show
    code-link: true
    code-summary: "Show the code"
    code-tools: true 
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>"
---

Hay un principio que a los advenedizos a este mundo se les olvida. El principio
KISS (Keep it simple Stupid). Me refiero a que hay gente que cree que hay que probar 20 tipos de modelos, hacer una búsqueda intensiva de hiperparámetros, aumentar la profundidad de los modelos, hacer submuestreo a mansalva, inventar fórmulas de calibración  que puede que no lleven a nada o entrenar modelos de forma automática casi sin supervisión humana. 

Pues no amigos míos, eso no es ser científico de datos , eso es ser un churrero robotizado. Puede que tengas suerte haciendo eso incluso que te pagan un montón de dinero y piensen que eres un crack, pero es todo una farsa. 

Señal y ruido, cuando en los datos hay estructura, cuando hay señal, no hace falta probar 10 xgboost, 4 catboost, 5 lightgbm y 3 mierdas más, ni hacer búsqueda de hiperpárametos bayesiana vía optuna. Las mejoras al hacer todo esto serán si acaso marginales, lo que un verdadero científico de datos es limpiar datos, hablar con negocio, pensar variables que influyan en el target, ponerse en la piel del cliente que va a comprar o no el producto cuya propensión se está modelando.  Unos buenos datos y unas buenas variables hacen mucho más por el éxito de tu modelo que las chorrocientas mil técnicas que hayas aprendido en bootcamps de chichinabo. 

Un último consejo. Si os encontráis con gente que hace las cosas esas que he comentado, por favor, enseñadles un poquito de principio KISS, a la larga os lo agradecerán. Y si os llaman locos o no os hacen caso, quizá sea el momento de buscar inteligencia en otro sitio. 


