---
title: 'Jornadas de usuarios de R  (y ya van 11) '
date: '2019-05-04'
categories:
  - 2019    
  - estadística
  - machine learning
  - R
execute: 
  message: false
  warning: false
  echo: true
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8
    fig-align: center
knitr:
  opts_chunk:
    out.width: 80%
    fig.showtext: TRUE
    collapse: true
    comment: "#>"
---

Quién nos los iba a decir, allá por 2009 cuándo recién creada la lista de correo **r-help-es** nos llegó el [mensaje](https://stat.ethz.ch/pipermail/r-help-es/2009-July/000149.html) de que iban a celebrarse las primeras jornadas.Creo que soy, salvo que me corrija Emilio o Carlos, el que a más jornadas ha ido (sólo falté a las míticas de Mieres), jejejeje. 

Hoy en día hay muchos eventos relacionados con software libre, analítica, big data, machine learning etcétera. Sin quitar méritos a ninguno de ellos, en mi humilde (y sesgada) opinión las jornadas de R-Hispano son uno de los mejores eventos. Son unas jornadas asequibles para todo el mundo (45 € este año si te inscribes antes del 31 de Julio), y habrá charlas y talleres super interesantes. Se me olvidaba, una de las cosas que más me gusta es que hay cabida para todo tipo de charlas, desde las más avanzadas hasta primeras experiencias en el uso de R. 


Pues poco más que decir, que este año son en Madrid, que serán del 14 al 16 de Noviembre, __que vamos a traer a uno (o varios) de los "popes"__ en el mundo R a nivel internacional y que esperamos que os inscribáis y mandéis comunicaciones, presentaciones cortas y propuestas de talleres para el uso y disfrute de todos.

* [Enlace a las jornadas](http://r-es.org/XIjuR/)
* [Inscripción](https://docs.google.com/forms/d/1cMT-eQyftssGgtd2J6LqRsW-0t80UJX6eiZYEvT81CQ/edit)
* [Envío de propuestas](https://docs.google.com/forms/d/e/1FAIpQLSfPA8W1LT9gScB4-pBP2lxpfyxILezxhwnVxxDbq2pT7gIKUg/viewform)


